### ISSUE TITLE
Reader NFC

### ISSUE THREAD

**Issue by bkharrab** [LieBtrau/arduino-ntag#3]
Hi,

I wanted to write some data from the mobile phone and then read it on my NFC NT3H1101 device. But there are no "read" methode.

Thanks

**Comment by bkharrab** [comment]
Sorry NT3H1101 is just a ntag !

**Comment by LieBtrau** [comment]
The NT3H1101 contains EEPROM and SRAM memory.  These two memories are attached to an NFC interface and to an I²C interface.
You could use your mobile phone to write and read data from the tag using the NFC-interface..  The Arduino can read from and write data to the NT3H1101 using the I²C interface.

If you have another question, let me know.  Otherwise I'll close this issue next week.

**Comment by bkharrab** [comment]
Thank you LiBtrau for your respond but if you said the arduino can read from NT3H1101 using the I2C interface why I didn't find a read method in you library ?

**Comment by LieBtrau** [comment]
Hmm...I don't know why you didn't find it.  Maybe because I hid it so well ;-)?
Instead of using the ntagsramadapter-class, you should directly use the ntag-class.  That class contains four functions interesting to you: readeeprom, writeeeprom, readsram, writesram.
